# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: ko

# Timezone
timezone: Asia/Seoul

# SEO settings
title: Jaemin Devlog
tagline: 개발 기록 블로그
description: >-
  개발 공부와 기록을 위한 개인 블로그입니다.
url: "https://jaemin-devlog.github.io"

github:
  username: jaemin-devlog

twitter:
  username: # 트위터 안쓰면 그냥 비워둬도 됨

social:
  name: Jaemin
  email: jjm0203311@naver.com
  links:
    - https://github.com/jaemin-devlog
    - https://blog.naver.com/jjm0203311

# Site Verification Settings
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings
pageviews:
  provider:

# Color scheme
theme_mode: # [light | dark]

# CDN (안 쓰면 빈 값 유지)
cdn:

# Sidebar avatar
avatar: /assets/image/7c1f6e0a9064fabe370eec3e65bb9a26.jpg


# SEO preview image
social_preview_image:

# TOC
toc: true

# Comments
comments:
  provider: giscus
  giscus:
    repo: jaemin-devlog/jaemin-devlog.github.io
    repo_id: R_kgDOPBioZA
    category: General
    category_id: DIC_kwDOPBioZM4CsWnH
    mapping: pathname
    strict: false
    input_position: bottom
    lang: ko
    reactions_enabled: true



# Static assets
assets:
  self_host:
    enabled:
    env:

# PWA
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# Pagination
paginate: 10

# Base URL
url: "https://jaemin-devlog.github.io"
baseurl: ""

# Do not modify below unless 필요
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
